---
apiVersion: v1
kind: Service
metadata:
  name: geo-ip
spec:
  type: ClusterIP
  selector:
    app: geo-ip
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-ip
  template:
    metadata:
      labels:
        app: geo-ip
    spec:
      containers:
        - name: app
          image: geo-ip
          resources: {}
          env:
            - name: LOG_LEVEL
              value: info
            - name: HTTP_LISTEN
              value: ":80"
