---
apiVersion: v1
kind: Service
metadata:
  name: geo-ip
spec:
  type: ClusterIP
  selector:
    app: geo-ip
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-ip
  template:
    metadata:
      labels:
        app: geo-ip
    spec:
      containers:
        - name: app
          image: geo-ip
          resources: {}
          ports:
            - name: main
              containerPort: 80
          env:
            - name: LOG_LEVEL
              value: info
            - name: HTTP_LISTEN
              value: ":80"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: geo-ip
  labels:
    release: prometheus # release name of prom-stack chart
spec:
  selector:
    matchLabels:
      app: geo-ip
  podMetricsEndpoints:
    - port: main
      interval: 30s
      path: /metrics
      targetPort: 80
