---
apiVersion: v1
kind: Service
metadata:
  name: geo-ip
spec:
  type: ClusterIP
  selector:
    app: geo-ip
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geo-ip
spec:
  replicas: 1
  serviceName: geo-ip
  selector:
    matchLabels:
      app: geo-ip
  volumeClaimTemplates:
    - metadata:
        name: geo-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
  template:
    metadata:
      labels:
        app: geo-ip
    spec:
      initContainers:
        - name: geo-update
          image: maxmindinc/geoipupdate:latest
          resources: {}
          env:
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: geo-update
                  key: GEOIPUPDATE_ACCOUNT_ID
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: geo-update
                  key: GEOIPUPDATE_LICENSE_KEY
            - name: GEOIPUPDATE_EDITION_IDS
              value: GeoLite2-City
          volumeMounts:
            - mountPath: /usr/share/GeoIP
              name: geo-db
      containers:
        - name: app
          image: geo-ip
          resources: {}
          ports:
            - name: main
              containerPort: 80
          env:
            - name: LOG_LEVEL
              value: info
            - name: HTTP_LISTEN
              value: ":80"
          volumeMounts:
            - mountPath: /usr/share/GeoIP
              name: geo-db

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: geo-ip
  labels:
    release: prometheus # release name of prom-stack chart
spec:
  selector:
    matchLabels:
      app: geo-ip
  podMetricsEndpoints:
    - port: main
      interval: 30s
      path: /metrics
      targetPort: 80
